---
- name: Deploy C++ Redistributables to Windows VMs
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Set user creds
      ansible.builtin.set_fact:
        windows_username: ''
        windows_password: ''

- name: Install C++ Redistributables on Windows VMs
  hosts: windows_vms # leveraging inventory group 'windows_vms' for the target Windows machines
  gather_facts: false
  vars:
    ansible_user: "{{ hostvars['localhost']['windows_username'] }}"
    ansible_password: "{{ hostvars['localhost']['windows_password'] }}"
    ansible_connection: psrp
    ansible_psrp_auth: ntlm
    ansible_psrp_cert_validation: ignore
  tasks:
    - name: Ensure Temp directory exists
      ansible.windows.win_file:
        path: C:\Temp
        state: directory
      register: ensure_temp_dir

    - name: Download x86 Redistributable if not installed
      ansible.windows.win_get_url:
        url: https://aka.ms/vs/16/release/vc_redist.x86.exe
        dest: C:\Temp\vc_redist.x86.exe
      register: download_x86

    - name: Download x64 Redistributable if not installed
      ansible.windows.win_get_url:
        url: https://aka.ms/vs/16/release/vc_redist.x64.exe
        dest: C:\Temp\vc_redist.x64.exe
      register: download_x64

    - name: Install x86 Redistributable if not installed
      ansible.windows.win_package:
        path: C:\Temp\vc_redist.x86.exe
        arguments: /install /quiet /norestart
        state: present
      register: install_x86

    - name: Install x64 Redistributable if not installed
      ansible.windows.win_package:
        path: C:\Temp\vc_redist.x64.exe
        arguments: /install /quiet /norestart
        state: present
      register: install_x64

    - name: Check if reboot is required
      ansible.windows.win_reboot:
        reboot_timeout: 600
        msg: "Rebooting after installing C++ Redistributables."
      register: reboot_result

    - name: Clean up installer files
      ansible.windows.win_file:
        path: "{{ item }}"
        state: absent
      loop:
        - C:\Temp\vc_redist.x86.exe
        - C:\Temp\vc_redist.x64.exe
      register: cleanup_result
