---
- name: Gather Windows Credenials
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Set user creds
      ansible.builtin.set_fact:
        windows_username: ''
        windows_password: ''

- name: Install C++ Redistributables on Windows VMs
  hosts: windows_vms
  gather_facts: false
  vars:
    ansible_user: "{{ hostvars['localhost']['windows_username'] }}"
    ansible_password: "{{ hostvars['localhost']['windows_password'] }}"
    ansible_connection: psrp
    ansible_psrp_auth: ntlm
    ansible_psrp_cert_validation: ignore
  tasks:
    - name: Wait for system to become reachable over WinRM
      ansible.builtin.wait_for_connection:
        delay: 6
        timeout: 900
        sleep: 10

    - name: Ensure Temp directory exists
      ansible.windows.win_file:
        path: C:\Temp
        state: directory
      register: ensure_temp_dir

    - name: Download x86 Redistributable if not installed
      ansible.windows.win_get_url:
        url: https://aka.ms/vs/16/release/vc_redist.x86.exe
        dest: C:\Temp\vc_redist.x86.exe
      register: download_x86

    - name: Download x64 Redistributable if not installed
      ansible.windows.win_get_url:
        url: https://aka.ms/vs/16/release/vc_redist.x64.exe
        dest: C:\Temp\vc_redist.x64.exe
      register: download_x64

    - name: Install x86 Redistributable if not installed
      ansible.windows.win_package:
        path: C:\Temp\vc_redist.x86.exe
        arguments: /install /quiet /norestart
        state: present
      register: install_x86

    - name: Install x64 Redistributable if not installed
      ansible.windows.win_package:
        path: C:\Temp\vc_redist.x64.exe
        arguments: /install /quiet /norestart
        state: present
      register: install_x64

    - name: Check if reboot is required
      ansible.windows.win_reboot:
        reboot_timeout: 600
        msg: "Rebooting after installing C++ Redistributables."
      register: reboot_result

    - name: Wait for system to become reachable over WinRM
      ansible.builtin.wait_for_connection:
        delay: 6
        timeout: 900
        sleep: 10

    - name: Download VMware Tools 12.5.1 installer
      ansible.windows.win_get_url:
        url: https://packages.vmware.com/tools/releases/latest/windows/x64/VMware-tools-12.5.1-24649672-x64.exe
        dest: C:\Temp\VMware-tools-12.5.1-24649672-x64.exe
      register: download_vmware_tools

    - name: Install VMware Tools 12.5.1 with reboot suppressed
      ansible.windows.win_package:
        path: C:\Temp\VMware-tools-12.5.1-24649672-x64.exe
        arguments: /S /v"/qn REBOOT=ReallySuppress"
        state: present
      register: install_vmware_tools

    - name: Check if reboot is required after VMware Tools installation
      ansible.windows.win_reboot:
        reboot_timeout: 600
        msg: "Rebooting after installing VMware Tools 12.5.1."

    - name: Wait for system to become reachable over WinRM
      ansible.builtin.wait_for_connection:
        delay: 6
        timeout: 900
        sleep: 10

    - name: Clean up installer files
      ansible.windows.win_file:
        path: "{{ item }}"
        state: absent
      loop:
        - C:\Temp\vc_redist.x86.exe
        - C:\Temp\vc_redist.x64.exe
        - C:\Temp\VMware-tools-12.5.1-24649672-x64.exe
      register: cleanup_result
