version: '3.8'

services:
  ansible-runner:
    image: debian:12
    container_name: ansible_runner
    volumes:
      - ./:/workspace:rw
    working_dir: /workspace
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
    entrypoint: >
      sh -c "
      apt-get update &&
      apt-get install -y python3 python3-pip python3-venv sshpass software-properties-common &&
      python3 -m venv /venv &&
      . /venv/bin/activate &&
      pip install ansible pypsrp &&
      ansible-galaxy collection install ansible.windows &&
      ansible-galaxy collection install community.windows &&
      ansible-playbook -i windows_vms deploy_redistributables.yml
      "
